apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  jwtPrivateKey: NTExMWQ4OWYtZGRlNQ==
  logglyToken: NTExMWQ4OWYtZGRlNS00MjE0LTllMWUtMDBkZTcwOTM5ZTQ0
  amqpPassword: N1dZUHo0MTlzOWVhTk1XS3k3UlJmQXg1LTU5VU1UcDI=
  bcryptSalt: MTA=