apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    app: user-service
spec:
  replicas: 1
  template:
    metadata:
      name: user-service
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: ewangclarks/node-back-end:ptus
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8003
          env:
            - name: jwt_private_key
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwtPrivateKey
            - name: loggly_token
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: logglyToken
            - name: amqp_password
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: amqpPassword
            - name: db_connection_url
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: dbConnectionUrl
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config-map
                  key: nodeEnv
            - name: bcrypt_salt
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: bcryptSalt
      imagePullSecrets:
        - name: registry-credentials
      restartPolicy: Always
  selector:
    matchLabels:
      app: user-service
